name: bee-code-interpreter

services:
  executor-builder: # only builds the executor
    build: ./executor
    image: "${APP_EXECUTOR_IMAGE:-bee-code-interpreter-executor:local}"
    entrypoint: ["/bin/true"]
    restart: no
  
  executor-dumper: # dumps the executor image into a file in volume
    depends_on:
      executor-builder:
        condition: service_completed_successfully
    image: docker:dind
    privileged: true
    volumes:
      - k3s-images:/k3s-images
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        echo "Dumping the image ${APP_EXECUTOR_IMAGE:-bee-code-interpreter-executor:local}..." &&
        docker save ${APP_EXECUTOR_IMAGE:-bee-code-interpreter-executor:local} -o /k3s-images/executor.tar
    restart: no

  k3s:
    depends_on:
      executor-dumper:
        condition: service_completed_successfully
    image: "rancher/k3s:v1.29.7-k3s1"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      K3S_KUBECONFIG_MODE: 644
    volumes:
      - k3s-config:/etc/rancher/k3s
      - k3s-images:/var/lib/rancher/k3s/agent/images
    command: ["server", "--tls-san", "k3s"]
    healthcheck:
      test: ["CMD", "kubectl", "get", "serviceaccount", "default"]
  
  service:
    depends_on:
      k3s:
        condition: service_healthy
    build: .
    environment:
      APP_EXECUTOR_IMAGE: "${APP_EXECUTOR_IMAGE:-bee-code-interpreter-executor:local}"
      APP_FILE_STORAGE_PATH: "/storage"
    volumes:
      - k3s-config:/etc/rancher/k3s
      - ${APP_FILE_STORAGE_PATH:-/tmp/code-interpreter/files}:/storage
    ports:
      - "50051:50051"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        sed 's|127.0.0.1|k3s|g' /etc/rancher/k3s/k3s.yaml >/kubeconfig.yaml 2>/dev/null &&
        KUBECONFIG=/kubeconfig.yaml python -m code_interpreter

volumes:
  k3s-config:
  k3s-images:
