name: bee-code-interpreter

services:
  k3s:
    image: "rancher/k3s:v1.29.7-k3s1"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      K3S_KUBECONFIG_MODE: 644
    volumes:
      - k3s-config:/etc/rancher/k3s
      - ./.tmp/images:/var/lib/rancher/k3s/agent/images
    command: ["server", "--tls-san", "k3s"]
    healthcheck:
      test: ["CMD", "kubectl", "get", "serviceaccount", "default"]

  service:
    depends_on:
      k3s:
        condition: service_healthy
    build: .
    environment:
      APP_EXECUTOR_IMAGE: ${APP_EXECUTOR_IMAGE:-localhost/bee-code-interpreter-executor:local}
      APP_FILE_STORAGE_PATH: "/storage"
      KUBECONFIG: "/kubeconfig"
    volumes:
      - k3s-config:/etc/rancher/k3s
      - ${APP_FILE_STORAGE_PATH:-./.tmp/files}:/storage
    ports:
      - "50051:50051"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        sed 's|127.0.0.1|k3s|g' /etc/rancher/k3s/k3s.yaml >/kubeconfig.yaml 2>/dev/null &&
        python -m code_interpreter

volumes:
  k3s-config:
